"""model update

Revision ID: fe0c6b53921e
Revises: b2c4f8541808
Create Date: 2024-09-14 11:19:48.365347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0c6b53921e'
down_revision: Union[str, None] = 'b2c4f8541808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('diagnosis', sa.Text(), nullable=False))
    op.add_column('appointments', sa.Column('severity', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.drop_column('appointments', 'reason')
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_emrs_id'), 'emrs', ['id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_emrs_id'), table_name='emrs')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.add_column('appointments', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_column('appointments', 'severity')
    op.drop_column('appointments', 'diagnosis')
    # ### end Alembic commands ###
